#use_frameworks!

platform :ios, '11.0'

target 'TYSocialLibaray_Example' do
  pod 'TYSocialLibaray', :path => '../'

  target 'TYSocialLibaray_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
